# Generated by Django 4.1.7 on 2023-04-21 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import services.get_file_path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='name')),
                ('surname', models.CharField(blank=True, max_length=30, verbose_name='surname')),
                ('nickname', models.CharField(blank=True, max_length=100, unique=True, verbose_name='nickname')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=functools.partial(services.get_file_path.FilePath.get_path_with_unique_filename, *(), **{'file_path': 'images/profile/avatar'}), verbose_name='avatar')),
                ('followers', models.ManyToManyField(related_name='follow_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
