version: '3.8'

services:
  db:
#    restart: always
    container_name: ${PSQL_HOST}
    image: postgres:15.1
    environment:
      POSTGRES_DB: ${PSQL_DB}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pgsql_data:/var/lib/postgresql/data/

  backend:
    container_name: blog_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/blog/backend
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    container_name: blog_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./frontend:/blog/frontend
      - /blog/frontend/node_modules
    ports:
      - 4001:3000
    depends_on:
      - backend

volumes:
  pgsql_data: