# Generated by Django 4.1.5 on 2023-01-27 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import services.get_file_path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='name')),
                ('surname', models.CharField(blank=True, max_length=30, verbose_name='surname')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='date of birth')),
                ('photo', models.ImageField(blank=True, upload_to=services.get_file_path.FilePath.get_file_path, verbose_name='photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
