# Generated by Django 4.1.5 on 2023-01-27 22:31

from django.db import migrations, models
import services.get_file_path


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=services.get_file_path.FilePath.get_file_path, verbose_name='photo'),
        ),
    ]
