# Generated by Django 4.1.5 on 2023-01-27 23:03

from django.db import migrations, models
import services.get_file_path


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=services.get_file_path.FilePath.get_file_path, verbose_name='photo'),
        ),
    ]
