# Generated by Django 4.1.5 on 2023-01-27 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter phone in format +380XXXXXXXXX', regex='^\\+?3?8?[- 0]?[- (]?[- 0(]?[0-9]{2}\\)?([ -]?[0-9]){7}')], verbose_name='phone number'),
        ),
    ]
